spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tec_blog_db
    username: tec_blog_db
    password:  Abcdefgo611
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10

  batch:
    jdbc:
      initialize-schema: ALWAYS  # スキーマ初期化の設定（テーブル作成を自動で行う）
    job:
      enabled: true  # バッチジョブの有効化
    initialization:
      enabled: true  # バッチの初期化を有効にする